### ISSUE TITLE
QQunrecalled使微信闪退

### ISSUE THREAD

**Issue by 443289353** [fkzhang/QQUnrecalled#9]
最近微信闪退，无法打开，于是到xposed模块里去查错，最后所有模块都排除了，只要一启用QQunrecalled，重启生效后微信就会闪退，无法打开，清除数据后可打开一次，之后也无法打开。
OS是MIUI7

**Comment by kkzxak47** [comment]
我这里微信会卡loading

**Comment by 443289353** [comment]
经测试，7月7日的最新版已修复，感谢大神！
